### ISSUE TITLE
 Finalize Database Structure for the Project and Store the ERD

### ISSUE THREAD

**Issue by ZU3AIRE** [ZU3AIRE/MarkMe.UI#43]
### Tasks:

1. Review the current project requirements to identify all necessary entities and their attributes.
2. Define relationships between entities (e.g., one-to-one, one-to-many, or many-to-many).
3. Create the database schema and ensure normalization to avoid redundancy.
4. Design the ERD using Lucidchart or any preferred tool.
5. Export the ERD diagram in PNG or PDF format.
6. Add the exported ERD file to the repository under a docs or design folder.

### Acceptance Criteria:

1. Database schema reflects all project requirements.
2. ERD is clear and accurately represents the finalized database structure.
3. The ERD is stored in the repository and accessible to all team members.

### Resources
[Lucid Chart Link](https://lucid.app/lucidchart/db27ffdb-af6e-4185-99fb-7e374ab80c63/edit?viewport_loc=288%2C-145%2C1889%2C864%2C0_0&invitationId=inv_adc55751-9677-4007-9087-686777295774)

### How to commit
After making changes in the ERD, export the ERD as SVG and commit your new version in the linked branch
 ```43-finalize-database-structure-for-the-project-and-store-the-erd```

**Comment by ZU3AIRE** [comment]
@muhammad-mousa The tables with their respective fields are added in ERD
Could you please add relationships in it, ASAP?

**Comment by muhammad-mousa** [comment]
@ZU3AIRE I have added relationships with the entities and commit my changes.
Please let me know, if there is any changes needed.

**Comment by ZU3AIRE** [comment]
Class Representative has one-many relationship with course and student .

Like for one course there can be at most five class representative and one student can be class representative of mant courses like some courses from the previous semesters...

@muhammad-mousa
